language: cpp

cache:
  ccache: true

env:
  # ccache
  - USE_CCACHE=1
  - CCACHE_COMPRESS=1
  - CCACHE_MAXSIZE=200M
  - CCACHE_CPP2=1

matrix:
  include:
    - os: osx
      osx_image: xcode9.4
      env:
       - CMAKE_PREFIX_PATH=/usr/local/opt/qt5/lib/cmake
       - CEF_BUILD_VERSION=3770
      before_install: "./CI/install-dependencies-osx.sh"
      before_script: "./CI/before-script-osx.sh"
      before_deploy: "./CI/before-deploy-osx.sh"

script: cd ./build && make -j4 && cd -

deploy:
  provider: releases
  api_key: $GITHUB_TOKEN
  file_glob: true
  file: nightly/*
  skip_cleanup: true
  on:
    repo: RickP/obs-studio
    tags: true
